title: Machine Learning Project Title
description: CS 4641 Machine Learning Project
author: Austin, ...
theme: just-the-docs

url: https://cs4641_abarton51.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
